version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: configs/docker/Dockerfile.backend
    container_name: web-scraper-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - ./storage:/app/storage
      - ./recipes:/app/recipes
    networks:
      - web-scraper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    container_name: web-scraper-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - web-scraper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web-scraper-network:
    driver: bridge

volumes:
  storage:
    driver: local
