version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: configs/docker/Dockerfile.backend
      target: deps
    container_name: web-scraper-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - ./storage:/app/storage
      - ./recipes:/app/recipes
    networks:
      - web-scraper-network
    restart: unless-stopped
    command: npm run dev

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
      target: deps
    container_name: web-scraper-frontend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - web-scraper-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3001

networks:
  web-scraper-network:
    driver: bridge

volumes:
  storage:
    driver: local
